version: "3"

services:
  panel:
    build: .
    depends_on:
      - panel-database
    ports:
      - 80:80
    volumes:
      - .:/var/www/html

  panel-database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - ./dbData:/var/lib/mysql
